### ISSUE TITLE
OptoWriter outputs OS errors after running for a while

### ISSUE THREAD

**Issue by tyoungNIO** [nio-blocks/opto_pac#4]
[2015-05-21 20:17:20.237] NIO [WARNING] [Sinulator_Evaluator_REB1.OptoWriterYOFF] Error sending packet, reconnecting. Exception: [Errno 32] Broken pipe
[2015-05-21 20:17:20.238] NIO [ERROR] [Sinulator_Evaluator_REB1.OptoWriterYOFF] Error processing signal {'sim1': 8762} : OSError [Errno 107] Transport endpoint is not connected

We have observed that this failure, on the ML400 (Broomfield LAN .89), does not seem to be caused by the total number of packets sent or the time running, but after some period (couple of hours) of running these errors show up and the Opto does not respond. Restarting services containing OptoWriter block causes normal operation to resume, for a while.

**Comment by mattdodge** [comment]
@tyoungNIO, can you confirm which version of the block this was running? It appears to be on the master branch based on the log messages you provided. You can check by `cd`ing into the opto_pac block folder and running `git branch`. 

I've created PR #5, it's probably about time we merge this in to the master branch but until then, you can grab the better_error_handling branch and use that.

**Comment by tyoungNIO** [comment]
Verified we are running Master branch, from within the opto_pac directory I did: git checkout better_error_handling, then git pull, and finally git branch shows we're on the new branch. Restarting services now, will update with results.

**Comment by tyoungNIO** [comment]
24 hour run time without failures on Linux, we will set up again on Windows and see what we get.

**Comment by tyoungNIO** [comment]
this is looking pretty good, when can it be merged? We're setting up OptoWriter testing on Windows rack server with better_error_handling brach

**Comment by hansmosh** [comment]
PR #5 has been merged
